<?php

/**
 * @author Monei Team
 * php version 8.1
 * @author    Monei <support@monei.com>
 * @copyright 2023 Monei
 * @link      https://monei.com/
 */

/** @var $block \Monei\MoneiPayment\Block\Info\Monei */
$paymentInfo = $block->getPaymentInfo();
?>
<?php if (is_array($paymentInfo)): ?>
    <?php $paymentMethodDisplay = $block->getFormattedPaymentMethodDisplay(); ?>

    <?php if (!empty($paymentMethodDisplay)): ?>
        <div class="admin__page-section-item-content">
            <span class="payment_details"><?= $escaper->escapeHtml($paymentMethodDisplay) ?></span>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="admin__page-section-item-content">
        <span class="payment_details"><?= $escaper->escapeHtml(__('Payment details will be available after payment confirmation')) ?></span>
    </div>
<?php endif; ?>
