<?php

/**
 * @author Monei Team
 * @copyright Copyright © Monei (https://monei.com)
 */

/** @var $block \Monei\MoneiPayment\Block\Info\Monei */
$paymentInfo = $block->getPaymentInfo();
?>
<?php if (is_array($paymentInfo)): ?>
    <?php $paymentMethodDisplay = $block->getFormattedPaymentMethodDisplay(); ?>

    <?php if (!empty($paymentMethodDisplay)): ?>
        <div class="admin__page-section-item-content">
            <?php if ($block->paymentMethodFormatter->getPaymentMethodIcon($paymentInfo)): ?>
                <?= /* @noEscape */ $block->paymentMethodFormatter->getPaymentMethodIconHtml($paymentInfo, ['class' => 'payment-icon', 'style' => 'margin-right: 6px; vertical-align: middle;']) ?>
            <?php endif; ?>
            <span class="payment_details"><?= $escaper->escapeHtml($paymentMethodDisplay) ?></span>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="admin__page-section-item-content">
        <span class="payment_details"><?= $escaper->escapeHtml(__('Payment details will be available after payment confirmation')) ?></span>
    </div>
<?php endif; ?>
