<?php
/** @copyright Copyright © Monei (https://monei.com) */

/** @var \Monei\MoneiPayment\Block\Payment\VaultRedirectForm $block */
?>
<form id="monei-vault-redirect-form"
      method="post"
      action="<?= $block->escapeUrl($block->getUrl('monei/payment/vaultredirect')) ?>"
      style="display: none;">
    <input type="hidden" name="form_key" value="<?= $block->escapeHtmlAttr($block->getFormKey()) ?>">
    <input type="hidden" name="public_hash" id="monei-vault-public-hash" value="">
</form>
