name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, tokenizer, json
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Download pretty-php
        run: |
          curl -L -o pretty-php.phar https://github.com/lkrms/pretty-php/releases/latest/download/pretty-php.phar
          chmod +x pretty-php.phar

      - name: Run PHP CS Fixer
        run: composer cs:check

      - name: Run PHPCS
        run: composer lint

      - name: Run pretty-php check
        run: composer pretty:check
