name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "monei-module-monei-payment.zip"
          exclusions: |
            *.git*
            *.github*
            *Test*
            .husky/*
            .yarn/*
            .vscode/*
            .cursor/*
            vendor/*
            composer.lock
            package.json
            yarn.lock
            .yarnrc.yml
            .nvmrc
            .prettierrc
            .prettierignore
            prettyphp.json
            pretty-php.phar*
            .cursorignore
            release-it.json
            commitlint.config.js
            bin

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: "monei-module-monei-payment.zip"
          artifactContentType: "application/zip"
          token: ${{ secrets.GITHUB_TOKEN }}
