name: Create Archive
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "monei-module-monei-payment-${{github.event.release.tag_name}}.zip"
          exclusions: "*.git*"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: "monei-module-monei-payment-${{github.event.release.tag_name}}.zip"
          artifactContentType: "application/zip"
          token: ${{ secrets.GITHUB_TOKEN }}
