name: monei-payment-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    name: 'MONEI Payment module tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      opensearch:
        image: opensearchproject/opensearch:1.2.1
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" -e "plugins.security.disabled=true" -e "plugins.security.ssl.http.enabled=false" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      ### Download the module code in custom dir###
      - uses: actions/checkout@v4
        with:
          path: MoneiPayment

      - name: 'install fresh magento repo'
        uses: MAD-I-T/magento-actions@v3.31
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'install-magento'
          magento_version: 2.4.7-p3
          php: 8.1
          no_push: 1 ## add this arg to not push to the repo ideal for quick test on specific version

      - name: 'Move module to Magento directory'
        run: |
          sudo mkdir -p ./magento/app/code/Monei/
          sudo mv ./MoneiPayment ./magento/app/code/Monei/
          sudo chown -R $USER:$GROUP ./magento/app/code/Monei/

      - name: 'Install dependencies'
        uses: php-actions/composer@v6
        with:
          working_dir: ./magento
          php_version: 8.1
          php_extensions: bcmath
          command: require monei/monei-php-sdk:^2.6 --ignore-platform-reqs --no-install
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}

      - name: 'Enable MONEI Payment module'
        run: |
          cd magento
          sudo bin/magento module:enable Monei_MoneiPayment
          sudo bin/magento setup:upgrade
          sudo bin/magento setup:di:compile
          sudo bin/magento cache:clean

      - name: 'launch magento2 unit test'
        uses: MAD-I-T/magento-actions@v3.31
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'unit-test'
          unit_test_config: 'dev/tests/unit/phpunit.xml.dist'
          unit_test_subset_path: 'app/code/Monei/MoneiPayment/'

      - name: 'phpstan'
        uses: MAD-I-T/magento-actions@v3.31
        with:
          process: 'phpstan'
          php: 8.1
          exec_path: 'app/code/Monei/MoneiPayment/'

      - name: 'mess detector'
        uses: MAD-I-T/magento-actions@v3.31
        with:
          process: 'mess-detector'
          php: 8.1
          md_src_path: 'app/code/Monei/MoneiPayment/'

      - name: 'Magento coding standard checking'
        uses: MAD-I-T/magento-actions@v3.31
        with:
          php: 8.1
          process: 'phpcs-test'
          extension: 'Monei_MoneiPayment'
          severity: 10
          standard: 'Magento2'
